// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/group/:groupName": {
    params: {
      "groupName": string;
    };
  };
  "/login": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/configs": {
    params: {};
  };
  "/dashboard/configs/new": {
    params: {};
  };
  "/dashboard/configs/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/models": {
    params: {};
  };
  "/dashboard/models/new": {
    params: {};
  };
  "/dashboard/models/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/templates": {
    params: {};
  };
  "/dashboard/templates/new": {
    params: {};
  };
  "/dashboard/templates/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/groups": {
    params: {};
  };
  "/dashboard/groups/new": {
    params: {};
  };
  "/dashboard/groups/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/history": {
    params: {};
  };
  "/dashboard/notifications": {
    params: {};
  };
  "/dashboard/notifications/new": {
    params: {};
  };
  "/dashboard/notifications/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/users": {
    params: {};
  };
  "/dashboard/system": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/group/:groupName" | "/login" | "/dashboard" | "/dashboard/configs" | "/dashboard/configs/new" | "/dashboard/configs/:id" | "/dashboard/models" | "/dashboard/models/new" | "/dashboard/models/:id" | "/dashboard/templates" | "/dashboard/templates/new" | "/dashboard/templates/:id" | "/dashboard/groups" | "/dashboard/groups/new" | "/dashboard/groups/:id" | "/dashboard/history" | "/dashboard/notifications" | "/dashboard/notifications/new" | "/dashboard/notifications/:id" | "/dashboard/users" | "/dashboard/system";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/group.$groupName.tsx": {
    id: "routes/group.$groupName";
    page: "/group/:groupName";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard" | "/dashboard/configs" | "/dashboard/configs/new" | "/dashboard/configs/:id" | "/dashboard/models" | "/dashboard/models/new" | "/dashboard/models/:id" | "/dashboard/templates" | "/dashboard/templates/new" | "/dashboard/templates/:id" | "/dashboard/groups" | "/dashboard/groups/new" | "/dashboard/groups/:id" | "/dashboard/history" | "/dashboard/notifications" | "/dashboard/notifications/new" | "/dashboard/notifications/:id" | "/dashboard/users" | "/dashboard/system";
  };
  "routes/dashboard._index.tsx": {
    id: "routes/dashboard._index";
    page: "/dashboard";
  };
  "routes/dashboard.configs.tsx": {
    id: "routes/dashboard.configs";
    page: "/dashboard/configs";
  };
  "routes/dashboard.configs_.new.tsx": {
    id: "routes/dashboard.configs_.new";
    page: "/dashboard/configs/new";
  };
  "routes/dashboard.configs_.$id.tsx": {
    id: "routes/dashboard.configs_.$id";
    page: "/dashboard/configs/:id";
  };
  "routes/dashboard.models.tsx": {
    id: "routes/dashboard.models";
    page: "/dashboard/models";
  };
  "routes/dashboard.models_.new.tsx": {
    id: "routes/dashboard.models_.new";
    page: "/dashboard/models/new";
  };
  "routes/dashboard.models_.$id.tsx": {
    id: "routes/dashboard.models_.$id";
    page: "/dashboard/models/:id";
  };
  "routes/dashboard.templates.tsx": {
    id: "routes/dashboard.templates";
    page: "/dashboard/templates";
  };
  "routes/dashboard.templates_.new.tsx": {
    id: "routes/dashboard.templates_.new";
    page: "/dashboard/templates/new";
  };
  "routes/dashboard.templates_.$id.tsx": {
    id: "routes/dashboard.templates_.$id";
    page: "/dashboard/templates/:id";
  };
  "routes/dashboard.groups.tsx": {
    id: "routes/dashboard.groups";
    page: "/dashboard/groups";
  };
  "routes/dashboard.groups_.new.tsx": {
    id: "routes/dashboard.groups_.new";
    page: "/dashboard/groups/new";
  };
  "routes/dashboard.groups_.$id.tsx": {
    id: "routes/dashboard.groups_.$id";
    page: "/dashboard/groups/:id";
  };
  "routes/dashboard.history.tsx": {
    id: "routes/dashboard.history";
    page: "/dashboard/history";
  };
  "routes/dashboard.notifications.tsx": {
    id: "routes/dashboard.notifications";
    page: "/dashboard/notifications";
  };
  "routes/dashboard.notifications_.new.tsx": {
    id: "routes/dashboard.notifications_.new";
    page: "/dashboard/notifications/new";
  };
  "routes/dashboard.notifications_.$id.tsx": {
    id: "routes/dashboard.notifications_.$id";
    page: "/dashboard/notifications/:id";
  };
  "routes/dashboard.users.tsx": {
    id: "routes/dashboard.users";
    page: "/dashboard/users";
  };
  "routes/dashboard.system.tsx": {
    id: "routes/dashboard.system";
    page: "/dashboard/system";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/group.$groupName": typeof import("./app/routes/group.$groupName.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/dashboard._index": typeof import("./app/routes/dashboard._index.tsx");
  "routes/dashboard.configs": typeof import("./app/routes/dashboard.configs.tsx");
  "routes/dashboard.configs_.new": typeof import("./app/routes/dashboard.configs_.new.tsx");
  "routes/dashboard.configs_.$id": typeof import("./app/routes/dashboard.configs_.$id.tsx");
  "routes/dashboard.models": typeof import("./app/routes/dashboard.models.tsx");
  "routes/dashboard.models_.new": typeof import("./app/routes/dashboard.models_.new.tsx");
  "routes/dashboard.models_.$id": typeof import("./app/routes/dashboard.models_.$id.tsx");
  "routes/dashboard.templates": typeof import("./app/routes/dashboard.templates.tsx");
  "routes/dashboard.templates_.new": typeof import("./app/routes/dashboard.templates_.new.tsx");
  "routes/dashboard.templates_.$id": typeof import("./app/routes/dashboard.templates_.$id.tsx");
  "routes/dashboard.groups": typeof import("./app/routes/dashboard.groups.tsx");
  "routes/dashboard.groups_.new": typeof import("./app/routes/dashboard.groups_.new.tsx");
  "routes/dashboard.groups_.$id": typeof import("./app/routes/dashboard.groups_.$id.tsx");
  "routes/dashboard.history": typeof import("./app/routes/dashboard.history.tsx");
  "routes/dashboard.notifications": typeof import("./app/routes/dashboard.notifications.tsx");
  "routes/dashboard.notifications_.new": typeof import("./app/routes/dashboard.notifications_.new.tsx");
  "routes/dashboard.notifications_.$id": typeof import("./app/routes/dashboard.notifications_.$id.tsx");
  "routes/dashboard.users": typeof import("./app/routes/dashboard.users.tsx");
  "routes/dashboard.system": typeof import("./app/routes/dashboard.system.tsx");
};